question_data = {
    "response_code": 0,
    "results": [
        {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
         "question": "What is Solid Snake&#039;s real name?", "correct_answer": "David",
         "incorrect_answers": ["Solid Snake", "John", "Huey"]},
        {"category": "Entertainment: Film", "type": "multiple", "difficulty": "easy",
         "question": "Which animated movie was first to feature a celebrity as a voice actor?",
         "correct_answer": "Aladdin",
         "incorrect_answers": ["Toy Story", "James and the Giant Peach", "The Hunchback of Notre Dame"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "The song &quot;Megalovania&quot; by Toby Fox made its third appearence in the 2015 RPG &quot;Undertale&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Sports", "type": "boolean", "difficulty": "easy",
         "question": "Manchester United won the 2013-14 English Premier League.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "Which of these bands are NOT from Australia?",
         "correct_answer": "The Naked and Famous",
         "incorrect_answers": ["Cut Copy", "Empire of the Sun", "Tame Impala"]},
        {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
         "question": "Who are the original creators of Rachet &amp; Clank?", "correct_answer": "Insomniac Games",
         "incorrect_answers": ["PixelTail Games", "Rare", "Bethesda"]},
        {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
         "question": "What is the maximum HP in Terraria?", "correct_answer": "500",
         "incorrect_answers": ["400", "1000", "100"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
         "question": "Druid is a mage class in &quot;Log Horizon&quot;.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science & Nature", "type": "multiple", "difficulty": "hard",
         "question": "How long is a light-year?",
         "correct_answer": "9.461 Trillion Kilometres",
         "incorrect_answers": ["1 AU", "105.40 Earth-years", "501.2 Million Miles"]},
        {"category": "Entertainment: Musicals & Theatres", "type": "multiple", "difficulty": "easy",
         "question": "What is Jean ValJean&#039;s first prisoner number?", "correct_answer": "24601",
         "incorrect_answers": ["9430", "1729", "32769"]}]}
